### ISSUE TITLE
规则增加

### ISSUE THREAD

**Issue by cloud-jie** [Monyer/antiHoneypot#4]
https://github.com/fuckhoneypot/fuckhoneypot

**Comment by Monyer** [comment]
#[007ff72](https://github.com/Monyer/antiHoneypot/commit/007ff7264482dc38ba8a35e902214d51e80f92e8)

**Comment by Monyer** [comment]
已在[007ff72](https://github.com/Monyer/antiHoneypot/commit/007ff7264482dc38ba8a35e902214d51e80f92e8)增加相关规则。
